# Site settings
title: DarkEdges
email: info@darkedges.com
description: "Identity and Access Management"
baseurl: ""
url: "https://lauris.github.io"
twitter_username: DarkEdges
github_username:  DarkEdges

google_analytics: UA-330453-2

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

paginate: 5

gems:
  - jekyll-sitemap
  - jekyll-paginate

